ARG BASE=python:3.9-alpine
ARG BASESLIM=python:3.9-slim
ARG TARGETBASE=alpine

##### BASE ALPINE

FROM ${BASE} AS basealpine-arm64
FROM ${BASE} AS basealpine-amd64

# ==== CLEAN BASE ====
FROM basealpine-${TARGETARCH}${TARGETVARIANT} AS alpine
# =====================
