name: test images

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.matrixTargets.outputs.targets }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - id: matrixTargets
        shell: bash
        run: |
          echo "targets=$(./build.py -h | grep 'positional arguments' -A1 | tail -n1 | sed 's/,/\n/g' | grep -ve all -e mixin$ -e ^base | jq -Rnc '{"target":[inputs]}')" >> $GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.targets) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - run: ./build.py ${{matrix.target}}
