name: test build

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.dataStep.outputs.myoutput }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - id: dataStep
        shell: bash
        run: |
          echo "myoutput=$(make | sed -e 's/ /\n/g' | jq -Rnc '{"target":[inputs]}')" >> $GITHUB_OUTPUT          
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    steps:
      - run: echo ${{matrix.target}}
